# Generated by Django 4.2.2 on 2023-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_imagetag_created_at_imagetag_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
