# Generated by Django 4.2.2 on 2023-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'no filter'), ('BLUR', 'blur'), ('CONTOUR', 'contour'), ('EDGE_ENHANCE', 'edge enhance'), ('EDGE_ENHANCE_MORE', 'edge enhance more'), ('SHARPEN', 'sharpen'), ('SMOOTH', 'smooth')], default='NO_FILTER', max_length=50),
            preserve_default=False,
        ),
    ]
