# Generated by Django 4.2.2 on 2023-06-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_image_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'No Filter'), ('BLUR', 'Blur'), ('CONTOUR', 'Contour'), ('EDGE_ENHANCE', 'Edge Enhance'), ('EDGE_ENHANCE_MORE', 'Edge Enhance More'), ('SHARPEN', 'Sharpen'), ('SMOOTH', 'Smooth')], max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
