# Generated by Django 4.2.2 on 2023-07-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_alter_image_action_alter_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='action',
            field=models.CharField(choices=[('NO_FILTER', 'No Filter'), ('BLUR', 'Blur'), ('CONTOUR', 'Contour'), ('EDGE_ENHANCE', 'Edge Enhance'), ('EDGE_ENHANCE_MORE', 'Edge Enhance More'), ('SHARPEN', 'Sharpen'), ('SMOOTH', 'Smooth'), ('GRAY', 'Gray')], max_length=50),
        ),
    ]
